# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-docstring-first
    -   id: check-builtin-literals
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: double-quote-string-fixer
-   repo: https://github.com/myint/docformatter
    rev: v1.5.0
    hooks:
    -   id: docformatter
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args: [
            --py311-plus,
            --application-directories=.:helpers
        ]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.0
    hooks:
    -   id: autopep8
        args: ['--in-place', '--ignore=E501,W504']
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args: [
            --py311-plus,
        ]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.2.3
    hooks:
    -   id: pyupgrade
        args: [--py311-plus]
